gcc -c instructions.c ram.c processor.c machine.c rom.c emulator.c main.c 
gcc instructions.c ram.c processor.c  machine.c main.c rom.c emulator.c -o exe ./lib/debug/x64/libprovided.a -lm $(sdl2-config --cflags --libs)
./exe
